# Generated by Django 2.2.4 on 2020-05-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('description_text_ru', models.TextField(verbose_name='Описание на ru')),
                ('description_text_eng', models.TextField(verbose_name='Описание на eng')),
                ('preview_image', models.ImageField(upload_to='images/products/', verbose_name='Превью')),
                ('detail_image_1', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
                ('detail_image_2', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
                ('detail_image_3', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
                ('detail_image_4', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='detail_image_1',
            field=models.ImageField(upload_to='images/brands', verbose_name='Внутреннее изобржение'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='detail_image_2',
            field=models.ImageField(upload_to='images/brands', verbose_name='Внутреннее изобржение'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='histiry_text_eng',
            field=models.TextField(verbose_name='описание на eng'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='histiry_text_ru',
            field=models.TextField(verbose_name='описание на ru'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='preview_image',
            field=models.ImageField(upload_to='images/brands', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
