# Generated by Django 2.2.4 on 2020-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_eng',
            field=models.CharField(default='', max_length=200, verbose_name='материал на eng'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ru',
            field=models.CharField(default='', max_length=200, verbose_name='материал на ru'),
        ),
        migrations.AddField(
            model_name='product',
            name='shape_eng',
            field=models.CharField(default='', max_length=200, verbose_name='Форма на eng'),
        ),
        migrations.AddField(
            model_name='product',
            name='shape_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Форма на ru'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=200, verbose_name='Индивидуальный номер'),
        ),
    ]
