# Generated by Django 2.2.4 on 2020-05-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200518_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text_ru', models.TextField(verbose_name='Описание на ru')),
                ('description_text_eng', models.TextField(verbose_name='Описание на eng')),
                ('date_time', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Дата и время проведения')),
                ('preview_image', models.ImageField(upload_to='images/products/', verbose_name='Превью')),
                ('detail_image_1', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
                ('detail_image_2', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
