# Generated by Django 2.2.4 on 2020-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='brand',
            name='title_eng',
            field=models.CharField(max_length=200, null=True, verbose_name='Название eng'),
        ),
        migrations.AddField(
            model_name='brand',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название ru'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_eng',
            field=models.CharField(max_length=200, null=True, verbose_name='Название события eng'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название события'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_eng',
            field=models.CharField(max_length=200, null=True, verbose_name='Название продукта eng'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название продукта ru'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='images/brands', verbose_name='Превью'),
        ),
    ]
