# Generated by Django 2.2.4 on 2020-06-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200602_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название проекта')),
                ('title_eng', models.CharField(max_length=200, null=True, verbose_name='Название проекта eng')),
                ('detail_image_1', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
                ('detail_image_2', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
                ('detail_image_3', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
                ('detail_image_4', models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение')),
                ('target_text_ru', models.TextField(verbose_name='Цель проекта на ru')),
                ('target_text_eng', models.TextField(verbose_name='цель проекта на eng')),
                ('description_text_ru', models.TextField(verbose_name='Описание на ru')),
                ('description_text_eng', models.TextField(verbose_name='Описание на eng')),
            ],
            options={
                'verbose_name': 'Проект в портфолио',
                'verbose_name_plural': 'Проекты в портфолию',
            },
        ),
    ]
