# Generated by Django 2.2.4 on 2020-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата и время проведения'),
        ),
    ]
