# Generated by Django 2.2.4 on 2020-06-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200603_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Превью'),
        ),
    ]
