# Generated by Django 2.2.4 on 2020-06-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_project_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_head',
            field=models.BooleanField(default=False, verbose_name='В шапку'),
        ),
    ]
