# Generated by Django 2.2.4 on 2020-06-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event_in_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/detail/', verbose_name='Внутреннее изображение'),
        ),
    ]
