# Generated by Django 2.2.4 on 2020-06-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200608_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Дата подачи заявки')),
                ('status', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Заявка на участие в мероприятии',
                'verbose_name_plural': 'Заявки на участие в мероприятиях',
            },
        ),
    ]
