# Generated by Django 2.2.4 on 2020-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_eventrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Дата подачи заявки')),
                ('status', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Заявка email расслку',
                'verbose_name_plural': 'Заявки на email рассылки',
            },
        ),
    ]
